---
title: "PI - Atividade 05"
author: "Ester Martins"
date: "20 de junho de 2018"
output: html_document
---
```{r}
5.1
# Para um vetor de 1 até 100, apresente o resultado final para as seguintes operações: adicionar a raiz quadrada do exponencial e dividir pela média do vetor.
V1 <- c()

for (i in 1:100) {
  V1[i] = i + sqrt(exp(i))
  y = mean(V1)
  z = V1/y
}
z
```
```{r}
5.2
# Para um vetor de 1 até 100, se o número for menor do que 20, exiba na tela pequeno. Se o número estiver entre 21 e 40, exiba médio. Se estiver entre 41 e 80, exiba grande. Se for igual a 100, exiba a palavra frango. Quando o número da vez for a sua idade, exiba Achei você!. Execute esta tarefa usando um loop for. (Obs.: Não use um número mágico para representar sua idade. Guarde-a num objeto chamado minha_idade.)
minha_idade <- 18
for (i in 1:100) {
  if (i <= 20) {
    print("Pequeno")
  }
  if (i > 20 & i <= 40 & i != minha_idade) {
    print("Médio")
  }
  if (i > 40 & i <= 80) {
    print("Grande")
  }
  if (i == minha_idade) {
    print("Achei você!")
  }
  if (i == 100) {
    print("Frango")
  }
}
```
```{r}
5.3
# Execute a mesma tarefa anterior usando um loop while.
x = 0
while (x <= 100) {
  x = x + 1
  if (x <= 20) {
    print("Pequeno")
  }
  if (x > 20 & x <= 40 & x != minha_idade) {
    print("Médio")
  }
  if (x > 40 & x <= 80) {
    print("Grande")
  }
  if (x == minha_idade) {
    print("Achei você!")
  }
  if (x == 100) {
    print("Frango")
  }
}
```
```{r}
5.4
# Crie uma matriz vazia de tamanho 10 X 10. Usando for loops, preencha a matriz de modo que ela fique assim:
##       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
##  [1,]    0   -1   -2   -3   -4   -5   -6   -7   -8    -9
##  [2,]    1    0   -1   -2   -3   -4   -5   -6   -7    -8
##  [3,]    2    1    0   -1   -2   -3   -4   -5   -6    -7
##  [4,]    3    2    1    0   -1   -2   -3   -4   -5    -6
##  [5,]    4    3    2    1    0   -1   -2   -3   -4    -5
##  [6,]    5    4    3    2    1    0   -1   -2   -3    -4
##  [7,]    6    5    4    3    2    1    0   -1   -2    -3
##  [8,]    7    6    5    4    3    2    1    0   -1    -2
##  [9,]    8    7    6    5    4    3    2    1    0    -1
## [10,]    9    8    7    6    5    4    3    2    1     0

A = matrix(0, nrow = 10, ncol = 10)

for(l in 0:nrow(A)){
    for(j in 0:ncol(A)){
        A[l,j]=l - j
    } 
}
A
```
```{r}
5.5
# Crie uma matriz vazia de tamanho 10 X 10. Usando for loops, preencha a matriz de modo que ela fique assim:
##       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
##  [1,]    2    3    4    5    6    7    8    9   10    11
##  [2,]    3    4    5    6    7    8    9   10   11    12
##  [3,]    4    5    6    7    8    9   10   11   12    13
##  [4,]    5    6    7    8    9   10   11   12   13    14
##  [5,]    6    7    8    9   10   11   12   13   14    15
##  [6,]    7    8    9   10   11   12   13   14   15    16
##  [7,]    8    9   10   11   12   13   14   15   16    17
##  [8,]    9   10   11   12   13   14   15   16   17    18
##  [9,]   10   11   12   13   14   15   16   17   18    19
## [10,]   11   12   13   14   15   16   17   18   19    20
B = matrix(0, nrow = 10, ncol = 10)

for(w in 1:nrow(B)){
    for(e in 1:ncol(B)){
        B[w,e]= w + e
    } 
}
B
```
```{r}
5.6
# Crie uma matriz vazia de tamanho 10 X 10. Usando for loops, preencha a matriz de modo que ela fique assim:
##       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
##  [1,]    4    9   16   25   36   49   64   81  100   121
##  [2,]    9   16   25   36   49   64   81  100  121   144
##  [3,]   16   25   36   49   64   81  100  121  144   169
##  [4,]   25   36   49   64   81  100  121  144  169   196
##  [5,]   36   49   64   81  100  121  144  169  196   225
##  [6,]   49   64   81  100  121  144  169  196  225   256
##  [7,]   64   81  100  121  144  169  196  225  256   289
##  [8,]   81  100  121  144  169  196  225  256  289   324
##  [9,]  100  121  144  169  196  225  256  289  324   361
## [10,]  121  144  169  196  225  256  289  324  361   400

C = matrix(0, nrow = 10, ncol = 10)
a = 2
s = 2
for(a in 1:nrow(C)){
    for(s in 1:ncol(C)){
      C[a,s]= (a+s)^2
    } 
}
C
```
```{r}
5.7
# Você conseguiu descobrir um loop para exibir na tela a sequência de fibonacci?
seqc = c()
seqc[1] = 1
seqc [2] = 1

for (i in 3:20){
  seqc[i] = seqc[i-1] + seqc[i-2]
}

seqc
```








